### ISSUE TITLE
Some request get limited to 25 results

### ISSUE THREAD

**Issue by efrainvalles** [markciecior/ConnectPyse#11]
Thanks for your your work maintaining this API for Connectwise, simple to work with. how do you access more records. I know the API limits results to 25. how do you either paginate results or expand the pagesize of results to the limit of 1000 records?

**Comment by markciecior** [comment]
I added a few lines to the README showing how paging and filtering work.  The other attributes you can use are [here](https://github.com/markciecior/ConnectPyse/blob/66c8a88bac4dcd1cde42fd658b369a71dc7a0caa/cw_controller.py#L11).
