### ISSUE TITLE
Setup (New way)

### ISSUE THREAD

**Issue by nyteghost** [markciecior/ConnectPyse#13]
I am rather new to python. for the new way setup I am a bit confused. 

Create two variables which are passed to the constructor of the API classes.
URL = 'https://connectwise.mycompany.com/v4_6_release/apis/3.0'
AUTH = {'Authorization': 'Basic Wmdlasdkjfeklamwekf=', 'clientId': 'myClientIdKey'}

for URL= We have a cloud based so for this would i use, 'https://api-na.myconnectwise.net/v2021.1/apis/3.0' or 'https://na.myconnectwise.net/v2021.1/apis/3.0'

for AUTH = what/where does "Basic Wmdlasdkjfeklamwekf" come from? Am i suppose to use my Public/Private API key, there? I have entered the clientid we have.

Thank you for your help!

**Comment by markciecior** [comment]
There's an example showing how headers are created [here](https://gist.github.com/mekuls/b2eff455424cc9bad894#file-cwapi_contacts_example-py-L30).
