### ISSUE TITLE
Ticket Creation

### ISSUE THREAD

**Issue by nyteghost** [markciecior/ConnectPyse#21]
Here with another question. Trying to create a ticket, but keep getting error
`AttributeError("'dict' object has no attribute '__dict__'")`

Below is my code. Thanks again for all the help so far :)

`def createStafftopBlockTicket():
    ct = tickets_api.TicketsAPI(url=cw.cwURL, auth=cw.cwAUTH)
    ticketInfo = {
        "summary": "This is a test of the API broadcast system",
        "company": {
            "id":"company_id"
        },
        "board": {
            "name": "board_name"
        },
        "resources": "resource_to_assign"
    }
    print(ticketInfo)
    ct = ct.create_ticket(ticketInfo)`

**Comment by emichaud** [comment]
Hey @nyteghost,
the quick answer is that on the line where you assign a dict to variable ticketInfo  has a couple of issues, but are easily fixed.
The create_ticket api requires you provide a Ticket object rather than a dict object.  But you had the right idea as you'll see in the solution below.

Here are two examples of the setup for a new ticket.  Use the approach you like best. Hope this helps.


```
from connectpyse.service import tickets_api, ticket

company_id = 45 #the id of the company
board_id = 2 #the id of the board
summary = 'magical ticket creation tests'
resources = 'johnTheTech'  #should match a cw username
url = ''
auth = ''

def add_ticket_using_dot_notation():
	ticket = ticket.Ticket()
	ticket.company = company_id
	ticket.board = board_id
	ticket.summary = summary
	ticket.resources = resources
	
	ct = tickets_api.TicketsAPI(url=url, auth=auth)
	new_ticket = ct.create_ticket(ticket)

	
def add_ticket_using_dict():
	ticket = ticket.Ticket(json_dict={
             "company":company_id, 
             "board":board_id, 
             "summary":summary,
             "resources":resources })
	
	ct = tickets_api.TicketsAPI(url=url, auth=auth)
	new_ticket = ct.create_ticket(ticket)

```

**Comment by nyteghost** [comment]
Where are you getting  ticket.Ticket from?

**Comment by nyteghost** [comment]
Never mind I see where. for some reason mine is not working when i do it your way, but i have to change ticket to newTicket like below.
newTicket = ticket.Ticket(json_dict={
             "company":company_id, 
             "board":board_name, 
             "summary":summary,
             "resources":resources })

but when i try and use either one i get 

AttributeError: 'str' object has no attribute 'keys'

**Comment by nyteghost** [comment]
That seemed to have worked mostly. The problem I am having is the resources is not assigning though. Not sure why?

**Comment by emichaud** [comment]
I guessed on that one.  In the ticket object, it’s defined as a string, so I assumed member user name.  Need to probably check the CW dev site for confirmation.

Another approach you can try is setting “owner” to a member id.  That would give that member ownership.

 

 

From: nyteghost ***@***.***>
Reply-To: markciecior/ConnectPyse ***@***.***>
Date: Thursday, January 27, 2022 at 4:45 PM
To: markciecior/ConnectPyse ***@***.***>
Cc: cocoaev ***@***.***>, Mention ***@***.***>
Subject: Re: [markciecior/ConnectPyse] Ticket Creation (Issue #21)

 

That seemed to have worked mostly. The problem I am having is the resources is not assigning though. Not sure why?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by emichaud** [comment]
Hey @nyteghost,

my apologies, I should have tested that code before providing it. Added in corrections and tested both approaches.

here is a working example of creating a ticket using the json object and fields you wanted and with setting ownership to a specific member.

Here is a link to :  [CW Service Ticket API](https://developer.connectwise.com/Products/Manage/REST#/Tickets/postServiceTickets)
```
def add_ticket_using_dict():
	company_id = 19297 #the id of the company
	board_id = 87 #the id of the board
	summary = 'magical ticket creation tests 2'
	memberid = 269
	
	api = tickets_api.TicketsAPI(url=BASE_URL, auth=AUTH)
	
	#create ticket object
	ticket_obj = ticket.Ticket(json_dict={"company": {"id":company_id}, 
		"board":{"id":board_id}, 
		"summary":summary,
		"owner": {"id":memberid}})
	new_ticket = api.create_ticket(ticket_obj)
	return new_ticket
```

Here is an example that works using the dot notation:

```
def add_ticket_using_dot_notation():
	company_id = 19297 #the id of the company
	board_id = 87 #the id of the board
	summary = 'magical ticket creation tests'
	memberid = 269
	#create the ticket object and pre-populate fields
	t = ticket.Ticket()
	t.company = {"id":company_id}
	t.board = {"id":board_id}
	t.owner = {"id":memberid}
	t.summary = summary
	
	#call CW to create a ticket using the data in your previously created ticket object
	api = tickets_api.TicketsAPI(url=BASE_URL, auth=AUTH)
	new_ticket = api.create_ticket(t)
	return new_ticket
```

In terms of adding resources to a ticket - you cannot do it at ticket creation, at least I couldn't find a way to do so.  I believe first you create a ticket, then add a schedule entry to it.  Here is an example of how to do that:

```
def add_schedule_to_ticket(ticketId):
	api = schedule_entries_api.ScheduleEntriesAPI(url=BASE_URL, auth=AUTH)
	sch = schedule_entry.ScheduleEntry()
	sch.member = {"id":269}
	sch.objectId = ticketId
	sch.type = {"id":4}  #find these here: https://cwapi/v4_6_release/apis/3.0/schedule/types
	new_sch = api.create_schedule_entry(sch)
	return new_sch
	
	
sch = add_schedule_to_ticket(1196184)

```

Hope this helps you get this sorted.
