### ISSUE TITLE
Agreements Api failing to initialize

### ISSUE THREAD

**Issue by emichaud** [markciecior/ConnectPyse#7]
When I run this code:

def get_agreements():
	api = agreements_api.AgreementsAPI(url=BASE_URL, auth=AUTH)
	agreement_list = api.get_agreements()
	return {'agreements':agreement_list}
	
al = get_agreements()

I get this result:

Traceback (most recent call last):
  File "Untitled 2.py", line 54, in <module>
    al = get_agreements()
  File "Untitled 2.py", line 49, in get_agreements
    api = agreements_api.AgreementsAPI(url=BASE_URL, auth=AUTH)
TypeError: __init__() missing 1 required positional argument: 'base_url'

I have everything working with service tickets, but not sure how to initialize the Agreements API?

**Comment by markciecior** [comment]
It looks like the Agreements API doesn't make use of the CWController class, like every other API class does.  I'm guessing this class was missed when @joshuamsmith first wrote this.  I can update it in the next few days.

**Comment by emichaud** [comment]
thanks Mark, appreciate your hard work maintaining this project.

**Comment by joshuamsmith** [comment]
Glad to see the work continues!! Yep, I lost access (via job) to CW before I could finish all the classes. Keep up the good work!!

**Comment by markciecior** [comment]
Updated agreements API with [this](https://github.com/markciecior/ConnectPyse/commit/d4dcee9b0ebb974e1df9a8602829749844b664bf) commit, closing issue.
